### ISSUE TITLE
Needs metadata output

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Extension-Base-Fire#1]

**Comment by aruzicka555** [comment]
Pull request submitted - ready for testing

**Comment by bmarron18** [comment]
same error as first QAQC run

Internal error occurred within the program:
  Object reference not set to an instance of an object.
Stack trace:
   at Landis.Library.Metadata.DataTableExtensions.SetColumns[T](DataTable tbl)
   at Landis.Library.Metadata.MetadataTable`1..ctor(String filePath)
   at Landis.Extension.BaseFire.MetadataHandler.InitializeMetadata(Int32 Timestep, String MapFileName, String eventLogName, String summaryLogName)
   at Landis.Extension.BaseFire.PlugIn.Initialize()
   at Landis.Model.InitExtensions(ExtensionMain[] extensions)
   at Landis.Model.Run(String scenarioPath, IUserInterface ui)
   at Landis.App.Main(String[] args)

**Comment by rmscheller** [comment]
Completed?

**Comment by bmarron18** [comment]
Yes, close issue (see PWL55c_QAQC&RepoStd_Base Fire_20170529).
